### PR TITLE
Update 1-generate-https.md

### PR DESCRIPTION
**Pull request by earcanal**
Highlight important renewal step (that I didn't read)!

### CODE REVIEW

**Comment by vsoch** [comment]
How about under that showing / reminding them how to do that (view the code of this comment to see it)?

```bash
$ docker-compose stop nginx
```

**Comment by earcanal** [comment]
I might need to leave it to you do suggest the best way.  Mine was a lot uglier than that!

**Comment by vsoch** [comment]
Why what did you type?

**Comment by vsoch** [comment]
Yes for each of those docker stop / start you would also put nginx to specify the image. Any reason for not adding these to the docs? You don't think it will be helpful for other users?

**Comment by earcanal** [comment]
Very useful, I'm just not confident that I can get the syntax right!

**Comment by vsoch** [comment]
Given a container with name experiment:
```
docker stop experiment
sudo service nginx start
sudo certbot renew
sudo service nginx stop
docker start experiment
```

There you go :) Be confident!

**Pull request merged**
